/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/budgets`; params?: Router.UnknownInputParams; } | { pathname: `/card-detail`; params?: Router.UnknownInputParams; } | { pathname: `/claim`; params?: Router.UnknownInputParams; } | { pathname: `/control`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/hotel-booking`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/policies`; params?: Router.UnknownInputParams; } | { pathname: `/request-funds`; params?: Router.UnknownInputParams; } | { pathname: `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/team`; params?: Router.UnknownInputParams; } | { pathname: `/transaction-detail`; params?: Router.UnknownInputParams; } | { pathname: `/transactions`; params?: Router.UnknownInputParams; } | { pathname: `/travel`; params?: Router.UnknownInputParams; } | { pathname: `/trip-detail`; params?: Router.UnknownInputParams; } | { pathname: `/upload-receipt`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/budgets`; params?: Router.UnknownOutputParams; } | { pathname: `/card-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/claim`; params?: Router.UnknownOutputParams; } | { pathname: `/control`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/hotel-booking`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/policies`; params?: Router.UnknownOutputParams; } | { pathname: `/request-funds`; params?: Router.UnknownOutputParams; } | { pathname: `/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/team`; params?: Router.UnknownOutputParams; } | { pathname: `/transaction-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/transactions`; params?: Router.UnknownOutputParams; } | { pathname: `/travel`; params?: Router.UnknownOutputParams; } | { pathname: `/trip-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/upload-receipt`; params?: Router.UnknownOutputParams; } | { pathname: `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/budgets${`?${string}` | `#${string}` | ''}` | `/card-detail${`?${string}` | `#${string}` | ''}` | `/claim${`?${string}` | `#${string}` | ''}` | `/control${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/hotel-booking${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/policies${`?${string}` | `#${string}` | ''}` | `/request-funds${`?${string}` | `#${string}` | ''}` | `/setup${`?${string}` | `#${string}` | ''}` | `/team${`?${string}` | `#${string}` | ''}` | `/transaction-detail${`?${string}` | `#${string}` | ''}` | `/transactions${`?${string}` | `#${string}` | ''}` | `/travel${`?${string}` | `#${string}` | ''}` | `/trip-detail${`?${string}` | `#${string}` | ''}` | `/upload-receipt${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/budgets`; params?: Router.UnknownInputParams; } | { pathname: `/card-detail`; params?: Router.UnknownInputParams; } | { pathname: `/claim`; params?: Router.UnknownInputParams; } | { pathname: `/control`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/hotel-booking`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/policies`; params?: Router.UnknownInputParams; } | { pathname: `/request-funds`; params?: Router.UnknownInputParams; } | { pathname: `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/team`; params?: Router.UnknownInputParams; } | { pathname: `/transaction-detail`; params?: Router.UnknownInputParams; } | { pathname: `/transactions`; params?: Router.UnknownInputParams; } | { pathname: `/travel`; params?: Router.UnknownInputParams; } | { pathname: `/trip-detail`; params?: Router.UnknownInputParams; } | { pathname: `/upload-receipt`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
